export const FIREBASE_APIKEY = process.env.NEXT_PUBLIC_FIREBASE_APIKEY
export const FIREBASE_AUTHDOMAIN = process.env.NEXT_PUBLIC_FIREBASE_AUTHDOMAIN
export const FIREBASE_PROJECTID = process.env.NEXT_PUBLIC_FIREBASE_PROJECTID
export const FIREBASE_STORAGEBUCKET = process.env.FIREBASE_STORAGEBUCKET
export const FIREBASE_MESSAGESENDERID = process.env.FIREBASE_MESSAGESENDERID
export const FIREBASE_APPID = process.env.FIREBASE_APPID
export const FIREBASE_MEASUREMENTID = process.env.FIREBASE_MEASUREMENTID
